<a href="https://colab.research.google.com/github/Sithija97/Python-Projects/blob/main/module_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
from matplotlib import pyplot as plt
%matplotlib inline

In [2]:
from google.colab import files

uploaded = files.upload()

Saving shots_detection_data_set.xlsx to shots_detection_data_set.xlsx


In [3]:
# reading the csv file
df = pd.read_excel("shots_detection_data_set.xlsx",index_col=False)
df.head()


fv.st.hp  fv.bl.hp  fv.ds.hp  fv.im.hp  fv.ft.hp  fsv.st.ba  fsv.st.tha  \
0       1.0       1.0       1.0       1.0       1.0  39.050223  173.403701   
1       1.0       1.0       1.0       1.0       1.0  37.253919  175.260633   
2       1.0       1.0       1.0       1.0       1.0  27.533375  176.260343   
3       1.0       1.0       1.0       1.0       1.0  27.533375  176.260343   
4       1.0       1.0       1.0       1.0       1.0  28.542006  177.489025   

   fsv.st.bha  fsv.st.ff.ka  fsv.st.bf.ka  ...  bsv.im.bf.ka  bsv.im.hip.a  \
0  173.540083    170.547831    178.030230  ...    158.315253    171.014743   
1  171.888323    173.289234    172.546227  ...    173.043681    172.243327   
2  171.149777    168.745427    172.087051  ...    168.593886    164.264251   
3  171.149777    168.745427    172.087051  ...    168.593886    164.264251   
4  172.796671    168.898101    172.239548  ...    166.200577    171.605351   

   bsv.ft.ba  bsv.ft.tha  bsv.ft.bha  bsv.ft.ff.ka  bsv.ft.bf.ka  \
0        0.0  348.509848    2.215897    142.151989    173.945860   
1        0.0  299.921692  181.229959    173.876313    177.015762   
2        0.0  112.345479  107.445714    154.701123    166.084491   
3        0.0   92.179390   77.878870    150.949791    164.874773   
4        0.0  114.965641  108.770398    143.429059    163.295278   

   bsv.ft.hip.a  player                shot  
0    172.220420     1.0                pull  
1    182.289155     1.0                 cut  
2    167.794345     1.0     back foot drive  
3    165.237805     1.0  back foot deffence  
4    175.509456     1.0    front foot drive  

[5 rows x 67 columns]

In [ ]:
# average numbers for all columns
df.groupby('shot').mean()

fv.st.hp  fv.bl.hp  fv.ds.hp  fv.im.hp  fv.ft.hp  \
shot                                                                   
back foot deffence       1.0       1.0       1.0       1.0       1.0   
back foot drive          1.0       1.0       1.0       1.0       1.0   
cut                      1.0       1.0       1.0       1.0       1.0   
front foot defence       1.0       1.0       1.0       1.0       1.0   
front foot drive         1.0       1.0       1.0       1.0       1.0   
pull                     1.0       1.0       1.0       1.0       1.0   

                    fsv.st.ba  fsv.st.tha    fsv.st.bha  fsv.st.ff.ka  \
shot                                                                    
back foot deffence  27.430692  176.510343  1.714831e+02    168.245427   
back foot drive     27.446342  176.050343  1.717313e+02    168.406594   
cut                 37.247002  175.227300  1.431650e+12    172.985567   
front foot defence  32.342749  171.751325  1.694478e+02    171.879674   
front foot drive    27.658673  177.917358  1.727633e+02    168.564768   
pull                38.954029  173.178806  1.734433e+02    171.131156   

                    fsv.st.bf.ka  ...  bsv.im.ff.ka  bsv.im.bf.ka  \
shot                              ...                               
back foot deffence    172.003718  ...    153.020056    168.849719   
back foot drive       172.145384  ...    153.020056    168.849719   
cut                   172.662060  ...    171.457443    172.810348   
front foot defence    175.775888  ...    146.924055    166.200577   
front foot drive      171.906215  ...    146.924055    166.200577   
pull                  177.887308  ...    151.086940    158.305253   

                    bsv.im.hip.a  bsv.ft.ba  bsv.ft.tha  bsv.ft.bha  \
shot                                                                  
back foot deffence    163.347584   0.000000   92.179390   77.878870   
back foot drive       163.347584   0.000000  112.178812  106.612381   
cut                   172.126660   0.000000  299.163359   15.102497   
front foot defence    172.022018   0.000000  111.502215  106.301999   
front foot drive      172.022018   0.000000  114.965641  108.187065   
pull                  171.181410  57.770778  348.237265    2.378647   

                    bsv.ft.ff.ka  bsv.ft.bf.ka  bsv.ft.hip.a  player  
shot                                                                  
back foot deffence    151.616458    164.374773    165.154472     1.0  
back foot drive       154.867790    166.501158    168.294345     1.0  
cut                   173.959646    176.849095    181.789155     1.0  
front foot defence    146.924055    166.200577    172.022018     1.0  
front foot drive      143.095726    162.461945    176.259456     1.0  
pull                  142.204797    174.530943    172.303753     1.0  

[6 rows x 66 columns]

In [4]:
df.shot = pd.Categorical(df.shot)

In [5]:
df['shot'] = df.shot.cat.codes 

In [6]:
df

fv.st.hp  fv.bl.hp  fv.ds.hp  fv.im.hp  fv.ft.hp  fsv.st.ba  fsv.st.tha  \
0        1.0       1.0       1.0       1.0       1.0  39.050223  173.403701   
1        1.0       1.0       1.0       1.0       1.0  37.253919  175.260633   
2        1.0       1.0       1.0       1.0       1.0  27.533375  176.260343   
3        1.0       1.0       1.0       1.0       1.0  27.533375  176.260343   
4        1.0       1.0       1.0       1.0       1.0  28.542006  177.489025   
..       ...       ...       ...       ...       ...        ...         ...   
67       1.0       1.0       1.0       1.0       1.0  32.092749  170.334658   
68       1.0       1.0       1.0       1.0       1.0  32.092749  171.334658   
69       1.0       1.0       1.0       1.0       1.0  33.092749  173.334658   
70       1.0       1.0       1.0       1.0       1.0  32.092749  172.334658   
71       1.0       1.0       1.0       1.0       1.0  30.092749  174.334658   

    fsv.st.bha  fsv.st.ff.ka  fsv.st.bf.ka  ...  bsv.im.bf.ka  bsv.im.hip.a  \
0   173.540083    170.547831    178.030230  ...    158.315253    171.014743   
1   171.888323    173.289234    172.546227  ...    173.043681    172.243327   
2   171.149777    168.745427    172.087051  ...    168.593886    164.264251   
3   171.149777    168.745427    172.087051  ...    168.593886    164.264251   
4   172.796671    168.898101    172.239548  ...    166.200577    171.605351   
..         ...           ...           ...  ...           ...           ...   
67  168.447756    172.129674    173.692555  ...    167.200577    171.605351   
68  171.447756    171.129674    176.692555  ...    166.200577    174.605351   
69  169.447756    170.129674    175.692555  ...    168.200577    170.605351   
70  168.447756    173.129674    177.692555  ...    165.200577    171.605351   
71  166.447756    172.129674    174.692555  ...    166.200577    172.605351   

    bsv.ft.ba  bsv.ft.tha  bsv.ft.bha  bsv.ft.ff.ka  bsv.ft.bf.ka  \
0         0.0  348.509848    2.215897    142.151989    173.945860   
1         0.0  299.921692  181.229959    173.876313    177.015762   
2         0.0  112.345479  107.445714    154.701123    166.084491   
3         0.0   92.179390   77.878870    150.949791    164.874773   
4         0.0  114.965641  108.770398    143.429059    163.295278   
..        ...         ...         ...           ...           ...   
67        0.0  110.835548  107.551999    147.757388    167.200577   
68        0.0  112.835548  105.551999    146.757388    166.200577   
69        0.0  110.835548  106.551999    145.757388    168.200577   
70        0.0  111.835548  105.551999    148.757388    165.200577   
71        0.0  112.835548  108.551999    146.757388    166.200577   

    bsv.ft.hip.a  player  shot  
0     172.220420     1.0     5  
1     182.289155     1.0     2  
2     167.794345     1.0     1  
3     165.237805     1.0     0  
4     175.509456     1.0     4  
..           ...     ...   ...  
67    171.605351     1.0     3  
68    174.605351     1.0     3  
69    170.605351     1.0     3  
70    171.605351     1.0     3  
71    172.605351     1.0     3  

[72 rows x 67 columns]

In [7]:
df=df.dropna(how="any")

In [8]:
# determining inputs and target
inputs = df.drop(columns = ['shot'])
target = df[['shot']]

In [9]:
# split the dataset into train and test subsets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(inputs,target,train_size=0.67)

**using logistic regression model**

In [ ]:
# import the model
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(multi_class='ovr')

In [ ]:
# training the model
model.fit(X_train,y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:765: ConvergenceWarning: lbfgs failed to converge (status=2):
ABNORMAL_TERMINATION_IN_LNSRCH.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:765: ConvergenceWarning: lbfgs failed to converge (status=2):
ABNORMAL_TERMINATION_IN_LNSRCH.

Increase the number of iterations (max_iter) or sca

LogisticRegression(multi_class='ovr')

In [ ]:
# predicting the outputs
model.predict(X_test)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int8)

In [ ]:
# accuracy of the model
model.score(X_test,y_test)

0.22727272727272727

**using svm model**

In [ ]:
# import the model
from sklearn.svm import SVC
model = SVC()

In [ ]:
# training the model
model.fit(X_train,y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


SVC()

In [ ]:
# predicting the outputs
model.predict(X_test)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
      dtype=int8)

In [ ]:
# accuracy of the model
model.score(X_test,y_test)

0.09090909090909091

**random forest model**

In [ ]:
# importing random forest classifier from assemble module
from sklearn.ensemble import RandomForestClassifier

# creating a RF classifier
clf = RandomForestClassifier(n_estimators = 100) 

In [ ]:
# training the model
clf.fit(X_train,y_train)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  


RandomForestClassifier()

In [ ]:
# predicting the outputs
clf.predict(X_test)

array([5, 0, 1, 0, 1, 3, 1, 0, 4, 4, 5, 1, 2, 2, 3, 4, 1, 2, 2, 0, 0, 4],
      dtype=int8)

In [ ]:
# accuracy of the model
clf.score(X_test,y_test)

1.0

In [ ]:
import numpy as np
test_row=pd.DataFrame(X_test.iloc[0,:]).T
test_row

fv.st.hp  fv.bl.hp  fv.ds.hp  fv.im.hp  fv.ft.hp  fsv.st.ba  fsv.st.tha  \
11       1.0       1.0       1.0       1.0       1.0  39.031893  173.403701   

    fsv.st.bha  fsv.st.ff.ka  fsv.st.bf.ka  ...  bsv.im.ff.ka  bsv.im.bf.ka  \
11  173.520183    171.785231     178.03023  ...    151.689523    158.315253   

    bsv.im.hip.a  bsv.ft.ba  bsv.ft.tha  bsv.ft.bha  bsv.ft.ff.ka  \
11    172.014743  63.022666  348.509848    2.215897    142.151989   

    bsv.ft.bf.ka  bsv.ft.hip.a  player  
11     174.94586     172.22042     1.0  

[1 rows x 66 columns]

In [ ]:
clf.predict(test_row)

array([5], dtype=int8)

**gradient boost classification**

In [10]:
# importing classifier model
from sklearn.ensemble import GradientBoostingClassifier

In [11]:
# creating the classifier
clf = GradientBoostingClassifier(n_estimators=100, learning_rate=1.0,
    max_depth=1, random_state=0).fit(X_train, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/ensemble/_gb.py:494: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [12]:
# accuracy of the model
clf.score(X_test, y_test)

1.0